//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CshapeWinforBasic
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public string ID { get; set; }
        public string HoTen { get; set; }
        public byte[] Image { get; set; }
    }
}
